package io.lsdconsulting.lsd.mono.core.report

import io.lsdconsulting.lsd.mono.core.escapeHtml
import io.lsdconsulting.lsd.mono.core.model.ReportFile
import io.lsdconsulting.lsd.mono.core.model.ReportJson
import java.io.File
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption

/**
 * Writes ReportJson + a minimal HTML listing. Also copies the packaged
 * report-next single-file shell beside the report for interactive demo viewing.
 *
 * Honest limitation: the single-file shell still embeds spike sample data;
 * live JSON injection into the SVG UI is deferred.
 */
object ReportWriter {
    private const val SPIKE_RESOURCE = "/lsd-mono-core/report-next/lsd-report-next.single.html"
    private const val SPIKE_FILENAME = "lsd-report-next.single.html"

    fun writeReport(
        report: ReportJson,
        outputDir: File,
        statusCss: String,
    ): Path {
        outputDir.mkdirs()
        val safeName = sanitizeFilename(report.title)
        val jsonPath = outputDir.resolve("$safeName-report.json").toPath()
        val htmlPath = outputDir.resolve("$safeName-report.html").toPath()

        Files.writeString(jsonPath, toPrettyJson(report))
        Files.writeString(htmlPath, renderMinimalHtml(report))
        copySpikeShell(outputDir)

        return htmlPath
    }

    fun writeIndex(
        reportFiles: List<ReportFile>,
        outputDir: File,
    ): Path {
        outputDir.mkdirs()
        val index = outputDir.resolve("index.html").toPath()
        val rows =
            reportFiles.joinToString("\n") { rf ->
                """
                <tr class="${rf.status.escapeHtml()}">
                  <td><a href="${rf.filename.escapeHtml()}">${rf.title.escapeHtml()}</a></td>
                  <td>${rf.status.escapeHtml()}</td>
                </tr>
                """.trimIndent()
            }
        val html =
            """
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8"/>
              <title>LSD Mono reports</title>
              <style>
                body { font-family: system-ui, sans-serif; margin: 2rem; }
                table { border-collapse: collapse; width: 100%; }
                th, td { border-bottom: 1px solid #ccc; padding: .5rem; text-align: left; }
                .success { color: #15803d; }
                .warn { color: #a16207; }
                .error { color: #b91c1c; }
              </style>
            </head>
            <body>
              <h1>LSD Mono report index</h1>
              <p>Generated by <code>lsd-mono-core</code>. Interactive demo shell:
                 <a href="$SPIKE_FILENAME">$SPIKE_FILENAME</a> (sample data until JSON injection lands).</p>
              <table>
                <thead><tr><th>Report</th><th>Status</th></tr></thead>
                <tbody>
                $rows
                </tbody>
              </table>
            </body>
            </html>
            """.trimIndent()
        Files.writeString(index, html)
        copySpikeShell(outputDir)
        return index
    }

    fun writeComponentsStub(
        title: String,
        outputDir: File,
    ): Path {
        outputDir.mkdirs()
        val path = outputDir.resolve("components-report.html").toPath()
        val html =
            """
            <!DOCTYPE html>
            <html lang="en">
            <head><meta charset="UTF-8"/><title>${title.escapeHtml()}</title></head>
            <body>
              <h1>${title.escapeHtml()}</h1>
              <p>Component diagram rendering is <strong>deferred</strong> in lsd-mono-core
                 (greenfield path uses report-next sequence SVG; PlantUML component
                 diagrams remain legacy reference only).</p>
            </body>
            </html>
            """.trimIndent()
        Files.writeString(path, html)
        return path
    }

    private fun copySpikeShell(outputDir: File) {
        val stream =
            ReportWriter::class.java.getResourceAsStream(SPIKE_RESOURCE)
                ?: return
        stream.use { input ->
            Files.copy(
                input,
                outputDir.resolve(SPIKE_FILENAME).toPath(),
                StandardCopyOption.REPLACE_EXISTING,
            )
        }
    }

    private fun sanitizeFilename(title: String): String =
        title
            .replace(Regex("[^A-Za-z0-9._-]+"), "-")
            .trim('-')
            .ifBlank { "lsd-report" }
            .take(80)

    private fun renderMinimalHtml(report: ReportJson): String {
        val scenarios =
            report.scenarios.joinToString("\n") { s ->
                val facts =
                    if (s.facts.isEmpty()) {
                        "<p><em>No facts</em></p>"
                    } else {
                        "<ul>" +
                            s.facts.joinToString("") {
                                "<li><strong>${it.key.escapeHtml()}</strong>: ${it.value.escapeHtml()}</li>"
                            } +
                            "</ul>"
                    }
                """
                <section class="scenario ${s.status.escapeHtml()}" id="${s.id.escapeHtml()}">
                  <h2>${s.title.escapeHtml()}
                    <span class="badge">${s.status.escapeHtml()}</span>
                  </h2>
                  <div class="description">${s.description}</div>
                  <h3>Facts</h3>
                  $facts
                </section>
                """.trimIndent()
            }
        return """
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8"/>
              <meta name="viewport" content="width=device-width, initial-scale=1"/>
              <title>${report.title.escapeHtml()}</title>
              <style>
                :root { color-scheme: light dark; }
                body { font-family: system-ui, sans-serif; margin: 0; padding: 1.5rem; line-height: 1.45; }
                header { margin-bottom: 1.5rem; border-bottom: 1px solid #8884; padding-bottom: 1rem; }
                .meta { color: #666; font-size: .9rem; }
                .scenario { margin: 1.25rem 0; padding: 1rem; border-radius: 8px; border: 1px solid #8884; }
                .badge { font-size: .75rem; padding: .15rem .45rem; border-radius: 999px; margin-left: .5rem; }
                .success .badge { background: #bbf7d0; color: #14532d; }
                .warn .badge { background: #fde68a; color: #713f12; }
                .error .badge { background: #fecaca; color: #7f1d1d; }
                .note { background: #f1f5f9; padding: .75rem 1rem; border-radius: 6px; margin-top: 1.5rem; }
                @media (prefers-color-scheme: dark) {
                  .note { background: #1e293b; }
                  .success .badge { background: #14532d; color: #bbf7d0; }
                  .warn .badge { background: #713f12; color: #fde68a; }
                  .error .badge { background: #7f1d1d; color: #fecaca; }
                }
              </style>
            </head>
            <body>
              <header>
                <h1>${report.title.escapeHtml()}</h1>
                <p class="meta">${report.generator.escapeHtml()} · ${report.generatedAt.escapeHtml()}</p>
              </header>
              $scenarios
              <div class="note">
                <strong>Report Next UI:</strong> open
                <a href="$SPIKE_FILENAME">$SPIKE_FILENAME</a> for the interactive SVG shell
                (still sample-data-driven). Live ReportJson injection is deferred.
                Source spike: <code>integrations/lsd-mono-core/report-next/</code>.
              </div>
            </body>
            </html>
            """.trimIndent()
    }

    /**
     * Minimal JSON without a third-party serializer — enough for ReportJson today.
     */
    private fun toPrettyJson(report: ReportJson): String {
        fun esc(s: String): String =
            buildString {
                for (c in s) {
                    when (c) {
                        '\\' -> append("\\\\")
                        '"' -> append("\\\"")
                        '\n' -> append("\\n")
                        '\r' -> append("\\r")
                        '\t' -> append("\\t")
                        else -> append(c)
                    }
                }
            }

        val scenarios =
            report.scenarios.joinToString(",\n") { s ->
                val facts =
                    s.facts.joinToString(",\n") { f ->
                        """      {"key":"${esc(f.key)}","value":"${esc(f.value)}"}"""
                    }
                """
                |  {
                |    "id": "${esc(s.id)}",
                |    "title": "${esc(s.title)}",
                |    "status": "${esc(s.status)}",
                |    "description": "${esc(s.description)}",
                |    "facts": [
                |$facts
                |    ],
                |    "metrics": [],
                |    "participants": [],
                |    "events": []
                |  }
                """.trimMargin()
            }
        return """
            |{
            |  "title": "${esc(report.title)}",
            |  "generatedAt": "${esc(report.generatedAt)}",
            |  "generator": "${esc(report.generator)}",
            |  "scenarios": [
            |$scenarios
            |  ]
            |}
            """.trimMargin()
    }
}
