package io.lsdconsulting.lsd.mono.core.report

import io.lsdconsulting.lsd.mono.core.escapeHtml
import io.lsdconsulting.lsd.mono.core.model.DelayEventJson
import io.lsdconsulting.lsd.mono.core.model.DividerEventJson
import io.lsdconsulting.lsd.mono.core.model.LifelineEventJson
import io.lsdconsulting.lsd.mono.core.model.MessageEventJson
import io.lsdconsulting.lsd.mono.core.model.NoteEventJson
import io.lsdconsulting.lsd.mono.core.model.ReportFile
import io.lsdconsulting.lsd.mono.core.model.ReportJson
import io.lsdconsulting.lsd.mono.core.model.ScenarioJson
import io.lsdconsulting.lsd.mono.core.model.SectionEventJson
import io.lsdconsulting.lsd.mono.core.model.SpacerEventJson
import io.lsdconsulting.lsd.mono.core.model.forShell
import io.lsdconsulting.lsd.mono.core.model.shellPayloadScript
import io.lsdconsulting.lsd.mono.core.model.toJson
import java.io.File
import java.nio.file.Files
import java.nio.file.Path

/**
 * Writes ReportJson, a minimal HTML listing, and the report single-file shell
 * with `window.__LSD_REPORT__` injected so the SVG UI renders the captured scenario.
 * Message bodies are not in that script. They are written beside the diagram as
 * `<title>-payloads.js` and loaded when the inspector opens.
 * Embedded sample data is only the fallback when that global is absent.
 */
object ReportWriter {
    private const val SHELL_RESOURCE = "/lsd-mono-core/report/lsd-report.single.html"
    private const val SHELL_FILENAME = "lsd-report.single.html"
    private const val SAMPLE_PAYLOAD_RESOURCE = "/lsd-mono-core/report/lsd-report-payloads.js"
    private const val SAMPLE_PAYLOAD_FILENAME = "lsd-report-payloads.js"

    fun writeReport(
        report: ReportJson,
        outputDir: File,
        @Suppress("UNUSED_PARAMETER") statusCss: String,
    ): Path {
        outputDir.mkdirs()
        val safeName = sanitizeFilename(report.title)
        val jsonPath = outputDir.resolve("$safeName-report.json").toPath()
        val htmlPath = outputDir.resolve("$safeName-report.html").toPath()
        val diagramName = "$safeName-diagram.html"
        val payloadsName = "$safeName-payloads.js"
        val shellBundle = report.forShell()
        if (shellBundle.payloads.isNotEmpty()) {
            Files.writeString(outputDir.resolve(payloadsName).toPath(), shellPayloadScript(shellBundle.payloads))
        }
        val shell = renderShell(shellBundle.report, payloadsName.takeIf { shellBundle.payloads.isNotEmpty() })

        Files.writeString(jsonPath, report.toJson())
        Files.writeString(outputDir.resolve("report.json").toPath(), report.toJson())
        Files.writeString(outputDir.resolve(diagramName).toPath(), shell)
        Files.writeString(htmlPath, renderMinimalHtml(report, diagramName))
        // Shared "latest" shell. createIndex must not clobber an injected copy.
        Files.writeString(outputDir.resolve(SHELL_FILENAME).toPath(), shell)

        return htmlPath
    }

    fun writeIndex(
        reportFiles: List<ReportFile>,
        outputDir: File,
    ): Path {
        outputDir.mkdirs()
        val index = outputDir.resolve("index.html").toPath()
        val rows =
            reportFiles.joinToString("\n") { rf ->
                """
                <tr class="${rf.status.escapeHtml()}">
                  <td><a href="${rf.filename.escapeHtml()}">${rf.title.escapeHtml()}</a></td>
                  <td>${rf.status.escapeHtml()}</td>
                </tr>
                """.trimIndent()
            }
        val html =
            """
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8"/>
              <title>LSD Mono reports</title>
              <style>
                body { font-family: system-ui, sans-serif; margin: 2rem; }
                table { border-collapse: collapse; width: 100%; }
                th, td { border-bottom: 1px solid #ccc; padding: .5rem; text-align: left; }
                .success { color: #15803d; }
                .warn { color: #a16207; }
                .error { color: #b91c1c; }
              </style>
            </head>
            <body>
              <h1>LSD Mono report index</h1>
              <p>Generated by <code>lsd-mono-core</code>. Each report links to an interactive
                 sequence diagram of the captured scenario
                 (<a href="$SHELL_FILENAME">$SHELL_FILENAME</a> is the latest report).</p>
              <table>
                <thead><tr><th>Report</th><th>Status</th></tr></thead>
                <tbody>
                $rows
                </tbody>
              </table>
            </body>
            </html>
            """.trimIndent()
        Files.writeString(index, html)
        copyShellIfAbsent(outputDir)
        return index
    }

    private fun copyShellIfAbsent(outputDir: File) {
        val dest = outputDir.resolve(SHELL_FILENAME)
        if (!dest.exists()) dest.writeText(readShellTemplate())
        val payloads = outputDir.resolve(SAMPLE_PAYLOAD_FILENAME)
        if (payloads.exists()) return
        val stream = ReportWriter::class.java.getResourceAsStream(SAMPLE_PAYLOAD_RESOURCE) ?: return
        payloads.writeText(stream.bufferedReader().use { it.readText() })
    }

    /**
     * Packaged shell boots with `const re = window.__LSD_REPORT__ ?? sample`.
     * Inject the captured report immediately before that script so file:// viewing works.
     * `<` in JSON is escaped so a payload cannot close the script tag.
     */
    private fun renderShell(report: ReportJson, payloadsFile: String?): String {
        val template = readShellTemplate()
        val src =
            if (payloadsFile == null) ""
            else "window.__LSD_PAYLOADS_SRC__=\"${payloadsFile.replace("\\", "\\\\").replace("\"", "\\\"")}\";"
        val injection = "<script>${src}window.__LSD_REPORT__=${report.toJson().trim()};</script>\n"
        val marker = "<script>"
        val idx = template.indexOf(marker)
        return if (idx < 0) injection + template else template.substring(0, idx) + injection + template.substring(idx)
    }

    private fun readShellTemplate(): String {
        val stream =
            ReportWriter::class.java.getResourceAsStream(SHELL_RESOURCE)
                ?: error("Missing classpath resource $SHELL_RESOURCE")
        val raw = stream.bufferedReader().use { it.readText() }
        val hook = "window.__LSD_REPORT__??"
        if (hook in raw) return raw
        return raw.replace("const re=", "const re=window.__LSD_REPORT__??")
    }

    private fun sanitizeFilename(title: String): String =
        title
            .replace(Regex("[^A-Za-z0-9._-]+"), "-")
            .trim('-')
            .ifBlank { "lsd-report" }
            .take(80)

    private fun renderMinimalHtml(report: ReportJson, diagramName: String): String {
        val scenarios =
            report.scenarios.joinToString("\n") { s ->
                val facts =
                    if (s.facts.isEmpty()) {
                        "<p><em>No facts</em></p>"
                    } else {
                        "<ul>" +
                            s.facts.joinToString("") {
                                "<li><strong>${it.key.escapeHtml()}</strong>: ${it.value.escapeHtml()}</li>"
                            } +
                            "</ul>"
                    }
                """
                <section class="scenario ${s.status.escapeHtml()}" id="${s.id.escapeHtml()}">
                  <h2>${s.title.escapeHtml()}
                    <span class="badge">${s.status.escapeHtml()}</span>
                  </h2>
                  <div class="description">${s.description.escapeHtml()}</div>
                  ${errorBlock(s)}
                  <h3>Facts</h3>
                  $facts
                  <h3>Sequence (${s.events.size})</h3>
                  ${eventList(s)}
                </section>
                """.trimIndent()
            }
        return """
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8"/>
              <meta name="viewport" content="width=device-width, initial-scale=1"/>
              <title>${report.title.escapeHtml()}</title>
              <style>
                :root { color-scheme: light dark; }
                body { font-family: system-ui, sans-serif; margin: 0; padding: 1.5rem; line-height: 1.45; }
                header { margin-bottom: 1.5rem; border-bottom: 1px solid #8884; padding-bottom: 1rem; }
                .meta { color: #666; font-size: .9rem; }
                .scenario { margin: 1.25rem 0; padding: 1rem; border-radius: 8px; border: 1px solid #8884; }
                .badge { font-size: .75rem; padding: .15rem .45rem; border-radius: 999px; margin-left: .5rem; }
                .success .badge { background: #bbf7d0; color: #14532d; }
                .warn .badge { background: #fde68a; color: #713f12; }
                .error .badge { background: #fecaca; color: #7f1d1d; }
                .note { background: #f1f5f9; padding: .75rem 1rem; border-radius: 6px; margin-top: 1.5rem; }
                @media (prefers-color-scheme: dark) {
                  .note { background: #1e293b; }
                  .success .badge { background: #14532d; color: #bbf7d0; }
                  .warn .badge { background: #713f12; color: #fde68a; }
                  .error .badge { background: #7f1d1d; color: #fecaca; }
                }
              </style>
            </head>
            <body>
              <header>
                <h1>${report.title.escapeHtml()}</h1>
                <p class="meta">${report.generator.escapeHtml()} · ${report.generatedAt.escapeHtml()}</p>
              </header>
              $scenarios
              <div class="note">
                <strong>Interactive diagram:</strong>
                <a href="${diagramName.escapeHtml()}">${diagramName.escapeHtml()}</a>
                renders this report (injected as <code>window.__LSD_REPORT__</code>).
                JSON: <a href="report.json">report.json</a>.
              </div>
            </body>
            </html>
            """.trimIndent()
    }

    private fun errorBlock(scenario: ScenarioJson): String {
        val error = scenario.error ?: return ""
        val stack =
            error.stack?.let { "<pre>${it.escapeHtml()}</pre>" }.orEmpty()
        return """
            <h3>${error.headline.escapeHtml()}</h3>
            <p>${error.message.escapeHtml()}</p>
            $stack
        """.trimIndent()
    }

    private fun eventList(scenario: ScenarioJson): String {
        if (scenario.events.isEmpty()) return "<p><em>No events</em></p>"
        val items =
            scenario.events.joinToString("") { event ->
                val label =
                    when (event) {
                        is MessageEventJson -> "${event.from} → ${event.to}: ${event.label} (${event.type})"
                        is NoteEventJson -> {
                            val anchor = event.over?.let { " $it" }.orEmpty()
                            "note ${event.placement}$anchor: ${event.text}"
                        }
                        is DividerEventJson -> "—— ${event.label}"
                        is SectionEventJson -> "section: ${event.title}"
                        is DelayEventJson -> "delay${event.label?.let { ": $it" }.orEmpty()}"
                        is SpacerEventJson -> "spacer${event.heightPx?.let { " ${it}px" }.orEmpty()}"
                        is LifelineEventJson -> "${event.kind} ${event.participantId}"
                    }
                "<li>${label.escapeHtml()}</li>"
            }
        return "<ol>$items</ol>"
    }
}
